force-app/main/src/objects/HttpConfig__mdt/HttpConfig__mdt.object-meta.xml
<CustomObject>
    <description>Http Configuration used by Salesforce to query off platform APIs.</description>
    <label>Http Config</label>
    <pluralLabel>Http Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpConfig__mdt/fields/ClientCertificateName__c.field-meta.xml
<CustomField>
    <fullName>ClientCertificateName__c</fullName>
    <description>The Client Certificate Developer Name required by this API.</description>
    <label>Client Certificate Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HttpConfig__mdt/fields/IsCompressed__c.field-meta.xml
<CustomField>
    <fullName>IsCompressed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the data in the body is delivered to the endpoint in the gzip compressed format. If false, no compression format is used.</description>
    <inlineHelpText>If true, the data in the body is delivered to the endpoint in the gzip compressed format. If false, no compression format is used.</inlineHelpText>
    <label>Is Compressed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HttpConfig__mdt/fields/IsIgnoreNulls__c.field-meta.xml
<CustomField>
    <fullName>IsIgnoreNulls__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If true, remove null values before serializing the JSON Payloads.</description>
    <inlineHelpText>If true, remove null values before serializing the JSON Payloads.</inlineHelpText>
    <label>Is Ignore Nulls?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/src/objects/HttpConfig__mdt/fields/TimeoutLimit__c.field-meta.xml
<CustomField>
    <fullName>TimeoutLimit__c</fullName>
    <defaultValue>1000 * 5</defaultValue>
    <description>How long to wait for a response before giving up in milliseconds. Must be between 1 and 120000ms.</description>
    <inlineHelpText>How long to wait for a response before giving up in milliseconds. Must be between 1 and 120000ms.</inlineHelpText>
    <label>Timeout Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HttpConfigHeader__mdt/HttpConfigHeader__mdt.object-meta.xml
<CustomObject>
    <description>Headers associated with an Http Config.</description>
    <label>Http Config Header</label>
    <pluralLabel>Http Config Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpConfigHeader__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/src/classes/HttpConfig.cls
global class HttpConfig {
  // If this.name is set, then it's from a custom metadata record
  // If this.name is NOT set, then it's been created in Apex memory.
  private String name;

  global Map<String, String> headers = new Map<String, String>();
  global Map<String, String> queryParams = new Map<String, String>();
  global String clientCertName;
  global Integer wait_ms;
  global Boolean isCompressed;
  global Boolean isIgnoreNulls;

  private HttpConfigService configService = new HttpConfigService();
  @TestVisible
  private void setHttpConfigService(HttpConfigService service) {
    this.configService = service;
  }

  private HttpConfigHeaderService headerService = new HttpConfigHeaderService();
  @TestVisible
  private void setHttpConfigHeaderService(HttpConfigHeaderService service) {
    this.headerService = service;
  }

  global HttpConfig () {}

  public HttpConfig(final String name) {
    this.name = name;
    setByMetadata(getMetdata(name));
  }

  private HttpConfig(HttpConfig__mdt mdt) {
    setByMetadata(mdt);
  }

  public static HttpConfig fromMetdata(HttpConfig__mdt mdt) {
    HttpConfig cfg = new HttpConfig(mdt);
    return cfg;
  }

  public String getName() {
    return name;
  }

  private void setName(final String val) {
    this.name = val;
  }

  public Boolean isMetadataDefined() {
    return String.isNotBlank(name);
  }

  // Returns a new HttpConfig after appending newCfg to this.
  public HttpConfig appendConfig(HttpConfig newCfg) {
    HttpConfig mergedCfg = this.copy();
    if (newCfg == null) {
      return mergedCfg;
    }

    if (String.isNotBlank(newCfg.getName())) {
      mergedCfg.setName(newCfg.getName());
    }

    if (!newCfg.headers.isEmpty()) {
      mergedCfg.headers.putAll(newCfg.headers);
    }

    if (!newCfg.queryParams.isEmpty()) {
      mergedCfg.queryParams.putAll(newCfg.queryParams);
    }

    if (String.isNotBlank(newCfg.clientCertName)) {
      mergedCfg.clientCertName = newCfg.clientCertName;
    }

    if (newCfg.wait_ms != null) {
      mergedCfg.wait_ms = newCfg.wait_ms;
    }

    if (newCfg.isCompressed != null) {
      mergedCfg.isCompressed = newCfg.isCompressed;
    }

    if (newCfg.isIgnoreNulls != null) {
      mergedCfg.isIgnoreNulls = newCfg.isIgnoreNulls;
    }

    return mergedCfg;
  }

  private HttpConfig copy() {
    HttpConfig cfg = new HttpConfig();

    cfg.setName(this.name);
    cfg.headers = this.headers.clone();
    cfg.clientCertName = this.clientCertName;
    cfg.wait_ms = this.wait_ms;
    cfg.isCompressed = this.isCompressed;
    cfg.isIgnoreNulls = this.isIgnoreNulls;

    return cfg;
  }

  private void setByMetadata(HttpConfig__mdt mdt) {
    this.name = mdt.DeveloperName;
    this.clientCertName = mdt.ClientCertificateName__c;
    this.wait_ms = Integer.valueOf(mdt.TimeoutLimit__c);
    this.isCompressed = mdt.IsCompressed__c;
    this.isIgnoreNulls = mdt.IsIgnoreNulls__c;
    this.setHeaders(mdt.DeveloperName);
  }

  private void setHeaders(final String name) {
    List<HttpConfigHeader__mdt> headersConfigs = headerService.getByParent(name);
    Map<String, String> headers = new Map<String, String>();
    for (HttpConfigHeader__mdt header : headersConfigs) {
      headers.put(header.Key__c, header.Value__c);
    }

    if (headers.isEmpty()) {
      return;
    }

    this.headers.putAll(headers);
  }

  private HttpConfig__mdt getMetdata(final String name) {
    HttpConfig__mdt mdt = configService.getInstance(name);
    if (mdt == null) {
      throw new RuntimeException('No HttpConfig__mdt found by DeveloperName: ' + name);
    }
    return mdt;
  }
}