force-app/main/src/objects/HttpConfig__mdt/HttpConfig__mdt.object-meta.xml
<CustomObject>
    <description>Http Configuration used by Salesforce to query off platform APIs.</description>
    <label>Http Config</label>
    <pluralLabel>Http Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpConfig__mdt/fields/IsCompressed__c.field-meta.xml
<CustomField>
    <fullName>IsCompressed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, the data in the body is delivered to the endpoint in the gzip compressed format. If false, no compression format is used.</description>
    <inlineHelpText>If true, the data in the body is delivered to the endpoint in the gzip compressed format. If false, no compression format is used.</inlineHelpText>
    <label>Is Compressed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HttpConfig__mdt/fields/IsIgnoreNulls__c.field-meta.xml
<CustomField>
    <fullName>IsIgnoreNulls__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If true, remove null values before serializing the JSON Payloads.</description>
    <inlineHelpText>If true, remove null values before serializing the JSON Payloads.</inlineHelpText>
    <label>Is Ignore Nulls?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/src/objects/HttpConfig__mdt/fields/TimeoutLimit__c.field-meta.xml
<CustomField>
    <fullName>TimeoutLimit__c</fullName>
    <defaultValue>1000 * 5</defaultValue>
    <description>How long to wait for a response before giving up in milliseconds. Must be between 1 and 120000ms.</description>
    <inlineHelpText>How long to wait for a response before giving up in milliseconds. Must be between 1 and 120000ms.</inlineHelpText>
    <label>Timeout Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HttpConfigHeader__mdt/HttpConfigHeader__mdt.object-meta.xml
<CustomObject>
    <description>Headers associated with an Http Config.</description>
    <label>Http Config Header</label>
    <pluralLabel>Http Config Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpConfigHeader__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/support/default/classes/CascadeConfigTest.cls
@IsTest
private class CascadeConfigTest {
  private static final String CONFIG_GLOBAL = 'Global';
  private static final String CONFIG_PARENT = 'DadJokesAPI';
  private static final String CONFIG_CHILD = 'TestChild';
  private static final String HEADER_GLOBAL = 'GlobalUserAgent';
  private static final String HEADER_PARENT = 'DadJokesAccept';
  private static final String HEADER_CHILD = 'ChildAccept';

  private static final String API_URL = 'https://some.com';

  @IsTest
  static void it_should_cascade_configs() {
    HttpClient client = new HttpClient(API_URL, CONFIG_CHILD);
    System.Assert.isNotNull(client);

    HttpConfig__mdt globalMdt = HttpConfig__mdt.getInstance(CONFIG_GLOBAL);
    HttpConfig__mdt dadJokesMdt = HttpConfig__mdt.getInstance(CONFIG_PARENT);
    HttpConfig__mdt childMdt = HttpConfig__mdt.getInstance(CONFIG_CHILD);
    HttpConfigHeader__mdt globalHeaderMdt = HttpConfigHeader__mdt.getInstance(HEADER_GLOBAL);
    HttpConfigHeader__mdt dadJokesHeaderMdt = HttpConfigHeader__mdt.getInstance(HEADER_PARENT);
    HttpConfigHeader__mdt childHeaderMdt = HttpConfigHeader__mdt.getInstance(HEADER_CHILD);

    HttpConfig config = client.config;
    System.Assert.areEqual(childMdt.DeveloperName, config.getName());
    System.Assert.areEqual(childMdt.IsCompressed__c, config.isCompressed);
    System.Assert.areEqual(childMdt.IsIgnoreNulls__c, config.isIgnoreNulls);
    System.Assert.areEqual(childMdt.TimeoutLimit__c, config.wait_ms);
    System.Assert.areEqual(globalHeaderMdt.Value__c, config.headers.get(globalHeaderMdt.Key__c));
    System.Assert.areEqual(childHeaderMdt.Value__c, config.headers.get(childHeaderMdt.Key__c));

    System.Assert.areNotEqual(globalMdt.DeveloperName, config.getName());
    System.Assert.areNotEqual(dadJokesMdt.DeveloperName, config.getName());
    System.Assert.areNotEqual(dadJokesHeaderMdt.Value__c, config.headers.get(dadJokesHeaderMdt.Key__c));
  }
}